/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/room.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="Table" geometry={nodes.Table.geometry} material={materials['beech-veneer_(1)']} position={[0.022, 0.024, 1.359]} />
      <group name="DocHolder" position={[0.022, 0.024, 1.359]}>
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['beech-veneer_(1)']} />
        <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials['concrete_simple_(1)']} />
      </group>
      <group name="TV" position={[-3.905, 3.028, 0]} rotation={[0.004, -0.002, -0.096]}>
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.TV} />
        <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['Material.003']} />
      </group>
      <group name="Sofa" position={[1.536, 0.124, -3.054]}>
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.sofa} />
        <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={materials['iron_shiny_(1)']} />
      </group>
      <group name="SideTable" position={[-3.261, 0, 3.043]}>
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.marblesubstance001} />
        <mesh name="Plane023_1" geometry={nodes.Plane023_1.geometry} material={materials['concrete_simple_(1)']} />
      </group>
      <mesh name="Speakers" geometry={nodes.Speakers.geometry} material={materials.speaker1} position={[-3.999, 3.703, 3.397]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Speaker2" geometry={nodes.Speaker2.geometry} material={materials.speaker2} position={[-3.984, 3.703, -3.366]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="Wall2" geometry={nodes.Wall2.geometry} material={materials.stone_wall} position={[0.012, 0, -0.006]} />
      <mesh name="Light" geometry={nodes.Light.geometry} material={materials['Light.001']} position={[0.608, 2.137, -3.911]} rotation={[-Math.PI / 2, 0, Math.PI]} />
      <group name="D3" position={[0.441, 2.093, 0.076]} rotation={[0, -0.558, -Math.PI / 2]}>
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['iron_shiny_(1)']} />
        <mesh name="Plane031_1" geometry={nodes.Plane031_1.geometry} material={materials.game} />
      </group>
      <mesh name="Mat" geometry={nodes.Mat.geometry} material={materials['Material.005']} position={[0.428, 1.453, 1.214]} />
      <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={materials['KeyBoard_01.001']} position={[0.464, 1.509, 1.432]} rotation={[0, 1.571, 0]} />
      <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials['R_Mouse.001']} position={[0.268, 1.485, 0.241]} rotation={[-Math.PI / 2, 0, 1.402]} />
      <mesh name="DownLights" geometry={nodes.DownLights.geometry} material={materials.Light} position={[-3.997, 0.166, 0.02]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh name="Poster" geometry={nodes.Poster.geometry} material={materials.Material} position={[2.579, 3.039, -3.938]} rotation={[Math.PI / 2, 0, 0]} />
      <group name="Gaming_Chair" position={[2.505, 0, 0.983]} rotation={[-Math.PI / 2, 0, -0.923]}>
        <mesh name="Object_0" geometry={nodes.Object_0.geometry} material={materials.Mat_4894223220941_BUT_OFFICE_CHAIR_LOOT_leather_a} />
        <mesh name="Object_0_1" geometry={nodes.Object_0_1.geometry} material={materials.Mat_4894223220941_BUT_OFFICE_CHAIR_LOOT_leather_b} />
        <mesh name="Object_0_2" geometry={nodes.Object_0_2.geometry} material={materials.Mat_4894223220941_BUT_OFFICE_CHAIR_LOOT_metal} />
        <mesh name="Object_0_3" geometry={nodes.Object_0_3.geometry} material={materials.Mat_4894223220941_BUT_OFFICE_CHAIR_LOOT_plastic} />
      </group>
      <group name="D3001" position={[0.066, 2.093, 1.404]} rotation={[0, -0.015, -Math.PI / 2]}>
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['iron_shiny_(1).001']} />
        <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['game.001']} />
      </group>
      <group name="D3002" position={[0.406, 2.093, 2.728]} rotation={[0, 0.497, -Math.PI / 2]}>
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['iron_shiny_(1).002']} />
        <mesh name="Plane013_1" geometry={nodes.Plane013_1.geometry} material={materials['game.002']} />
      </group>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.room} />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['wood_american_cherry_(1)']} />
      <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['concrete_clean_(1)']} />
    </group>
  )
}

useGLTF.preload('/room.gltf')
